### ISSUE TITLE
Use Github Action

### ISSUE THREAD

**Issue by yukinarit** [yukinarit/envclasses#7]
The usage of CircleCI is still very little. I am not an expert on CicleCI, so I want to transfer my projects to using Github Action instead of CircleCI for the same purpose i.e. running tests :)

**Comment by alexmisk** [comment]
Hi! Do you want to use GitHub actions for the same purposes as CircleCI?

**Comment by yukinarit** [comment]
Hi! @alexmisk 

The usage of CircleCI is still very little. I want to transfer my projects to using Github Action instead of CircleCI for the same popose i.e. running tests :)
